## HMM with hmmlearn
https://hmmlearn.readthedocs.io/en/latest/tutorial.html

In [1]:
import numpy as np
from hmmlearn import hmm

np.random.seed(42)

##### generate samples, given intial probs, transistion matrix, mean, & covarience

In [2]:
model = hmm.GaussianHMM(n_components=3, covariance_type='full')

model.startprob_ = np.array([0.6, 0.3, 0.1])
model.transmat_ = np.array([[0.7, 0.2, 0.1],
                            [0.3, 0.5, 0.2],
                            [0.3, 0.3, 0.4]])
model.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
model.covars_ = np.tile(np.identity(2), (3, 1, 1))
X, Z = model.sample(100)
X

array([[-1.11188012e+00,  3.18902185e-01],
       [ 1.57921282e+00,  7.67434729e-01],
       [-5.80878134e-01, -5.25169807e-01],
       [ 2.41962272e-01, -1.91328024e+00],
       [ 8.16445081e-01, -1.52387600e+00],
       [-9.08024076e-01, -1.41230370e+00],
       [-6.29474961e-01,  5.97720467e-01],
       [-5.44382725e-01,  1.10922590e-01],
       [-6.00253850e-01,  9.47439821e-01],
       [-6.01706612e-01,  1.85227818e+00],
       [-5.33648804e-01, -5.52786232e-03],
       [ 5.82254491e+00,  8.77915635e+00],
       [ 5.77831304e+00, -1.80636028e+00],
       [ 7.38466580e-01,  1.71368281e-01],
       [-1.00908534e+00, -1.58329421e+00],
       [-4.60638771e-01,  1.05712223e+00],
       [-1.13055230e+00,  1.34428883e-01],
       [ 2.32307800e+00, -2.38832371e+00],
       [ 5.82122795e-01,  8.87748460e-01],
       [ 2.16078248e+00, -3.30921238e+00],
       [ 3.49184671e+00,  1.10996470e+01],
       [-1.10633497e+00, -1.19620662e+00],
       [ 3.83479542e+00, -2.70343862e+00],
       [ 3.

In [3]:
Z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1,
       2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### training hmm params & inferring hidden states

Note, since the EM algorithm is a gradient-based optimization method, it will generally get stuck in local optima. You should in general try to run fit with various initializations and select the highest scored model

In [4]:
remodel = hmm.GaussianHMM(n_components=3, covariance_type='full', n_iter=100)
remodel.fit(X)

GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=3, n_iter=100, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [5]:
remodel.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
remodel.monitor_

ConvergenceMonitor(history=[-349.6448670351954, -349.6412552932653], iter=10,
          n_iter=100, tol=0.01, verbose=False)

In [7]:
remodel.monitor_.converged

True

##### working with multiple sequences

In [8]:
X1 = [[0.5], [1.0], [-1.0], [0.42], [0.24]]
X2 = [[2.4], [4.2], [0.5], [-0.24]]

X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]

In [9]:
multi_hmm = hmm.GaussianHMM(n_components=3)
multi_hmm.fit(X, lengths)

GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=3, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)